### PR TITLE
Update profile config

### PR DESCRIPTION
**Pull request by mcortes19**
- Updated the profile config and modules.
- Added new modules: 
  - analytics
  - components
  - image_style_quality
  - quicklink
  - redirect
  - redis
  - retina_images
  - search_api_solr
  - shs
  - smtp
  - warmer

# Steps to test
- [x] Clone project and switch to branch
- [x] Move the cloned folder to the profiles folder
- [x] Add all the needed config listed in the [README](https://github.com/ManatiCR/trichechus/blob/feature/update-profle-config/README.md) file
- [x] Install the Drupal site using this profile
- [x] Confirm all the modules listed are enabled

### CODE REVIEW

**Comment by rigoucr** [comment]
Thx for all your work @mcortes19 , awesome PR, but I found some issues,  I noticed that you forgot to enable the following modules:
- components
- Redis
In the redis case, I think that we should keep it disable, but downloaded. 

Also it seems that We forgot to mention that  we required this other module enabled:
- inline form errors (Is part of the drupal core)

Other think that I notice here is that you didn't added the devel config here, was it intentional? or you forgot about it?

**Comment by mcortes19** [comment]
Thank you @rigoucr, sorry for forgetting the **devel** config. I already pushed a commit added the following:
- Added missed **devel** config
- Enable the **inline_form_errors** module

Furthermore, I check and realize  the **components** module is already enable (it's a listed as trichechus dependency and it must be enabled [see](https://github.com/ManatiCR/trichechus/blob/2af516debe54cf9c56c2af1c65e2b39a3b4ca2fd/trichechus.info.yml#L18))

Finally, **Redis** is already required but not enabled

**Comment by rigoucr** [comment]
Thx @mcortes19 !!! now it works as expected

**Review by rigoucr — APPROVED** [review]
:shipit:

**Pull request merged**
